name: Build AppImage

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LANG: en_US.UTF-8
  LS_ALL: en_US.UTF-8
  LANGUAGE: en_US:en
  PROGRAMS: alacenc faac flac lame mac oggenc opusenc sox ttaenc wavpack wvunpack

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set env
      run: |
        echo "RELEASE_DATE=$(date +%Y.%m.%d_%H.%M.%S)" >> ${GITHUB_ENV}
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        [[ "${GITHUB_REF_TYPE}"  = "tag" ]] && echo APPIMAGE_NAME="flacon-${GITHUB_REF_NAME:1}-x86_64.AppImage" >> $GITHUB_ENV
        [[ "${GITHUB_REF_TYPE}" != "tag" ]] && echo APPIMAGE_NAME="flacon-$(date +%Y.%m.%d_%H.%M.%S)-x86_64.AppImage" >> $GITHUB_ENV

        echo "==============================="
        export
        echo "-------------------------------"
        cat $GITHUB_ENV
        echo "==============================="

    - uses: actions/checkout@v3

    - name: Install packages
      run:  |
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get -y update
        sudo apt-get -y install locales
        sudo sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y ppa:flacon
        sudo apt-get -y update
        sudo apt-get -y install build-essential pkg-config cmake  qtbase5-dev qttools5-dev-tools qttools5-dev libuchardet-dev libtag1-dev
        sudo apt-get -y install flac mac alacenc vorbis-tools wavpack lame ttaenc faac opus-tools sox
        sudo apt-get -y install desktop-file-utils

    - name: Clone tools
      run: |
        git clone --depth 1 https://github.com/SokoloffA/nightly-tools.git ~/tools
        echo PATH=~/tools/appimage/usr/bin:$PATH >> $GITHUB_ENV
        echo LD_LIBRARY_PATH=~/tools/appimage/usr/lib >> $GITHUB_ENV

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cmake -E make_directory ${{github.workspace}}/build/app
        cp ${{github.workspace}}/misc/excludelist .

    - name: Run CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/app/usr -DAPPIMAGE_BUNDLE=Yes -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE

    - name: Build Flacon
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j 8

    - name: Install Flacon
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make install

    - name: Build AppImage dir
      working-directory: ${{github.workspace}}/build/app
      run: |
        echo "==============================="
        export PATH=~/tools/appimage/usr/bin:$PATH
        export LD_LIBRARY_PATH=~/tools/appimage/usr/lib
        echo "= Create symlinks ============="
        ln -sf usr/bin/flacon AppRun
        ln -sf usr/share/icons/hicolor/128x128/apps/flacon.png .
        ln -sf usr/share/applications/flacon.desktop .
        echo "= Add programs ================"
        for prog in ${PROGRAMS}; do echo " * Copy ${prog}"; src=$(which "$prog"); dest=${src#/}; cp -f "${src}" "usr/bin/"; done
        echo "= Build image ================="
        linuxdeploy --verbosity=3  --plugin qt --appdir "${{github.workspace}}/build/app"

    - name: Check AppImage dir
      run: |
        /bin/bash ~/tools/appdir-lint.sh ${{github.workspace}}/build/app

    - name: Check external programs
      working-directory: ${{github.workspace}}
      run: |
        scripts/check-extprograms.sh . ${{github.workspace}}/build/app/usr/bin

    - name: Build AppImage file
      working-directory: ${{github.workspace}}/build/app
      run: |
        appimagetool "${{github.workspace}}/build/app" "${{github.workspace}}/build/${{ env.APPIMAGE_NAME }}"


    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APPIMAGE_NAME }}
        path: "${{github.workspace}}/build/${{ env.APPIMAGE_NAME }}"
